pipeline:
  name: parent-pipe
  identifier: parentpipe
  projectIdentifier: palak_labs
  orgIdentifier: default
  tags: {}
  variables:
    - name: Tower_URL
      type: String
      description: ""
      required: false
      value: https://tower.example.com
  stages:
    - stage:
        name: dede
        identifier: dede
        description: ""
        type: Pipeline
        spec:
          org: default
          project: palak_labs
          pipeline: testchained
          inputs:
            identifier: testchained
            variables:
              - name: Tower_URL
                type: String
                value: <+input>
