pipeline:
  name: pipeline-repro
  identifier: pipelinerepro
  projectIdentifier: palak_labs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: guglu00
        identifier: guglu
        tags: {}
        template:
          templateRef: account.stage_T
          versionLabel: v1
